
DROP TABLE IF NOT EXISTS cdx;
DROP TABLE IF NOT EXISTS file_meta;
DROP TABLE IF NOT EXISTS fatcat_file;
DROP TABLE IF NOT EXISTS petabox;
DROP TABLE IF NOT EXISTS grobid;
DROP TABLE IF NOT EXISTS ingest_request;
DROP TABLE IF NOT EXISTS shadow;
