[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.yapf]
COLUMN_LIMIT = 96
INDENT_DICTIONARY_VALUE=true
ALLOW_SPLIT_BEFORE_DICT_VALUE=false

[tool.isort]
line_length = 96
